// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iojzyttykwjjkacnbywf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlvanp5dHR5a3dqamthY25ieXdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMTI2NzEsImV4cCI6MjA2NDU4ODY3MX0.HbSw7Rw11Q0dbVAPP5imHApR0Ff952mUUkxmD_Wws_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);